version: '3'
volumes:
  dados:
networks: 
  banco:
  web:
  fila:
services:
    db: 
      image: postgres:9.6
      volumes:
        # Volume dos dados
        - dados:/var/lib/postgresql/data
        # Scripts
        - ./scripts:/scripts
        - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      networks: 
        - banco
    frontend:
      image: nginx:1.13
      volumes:
        #Site
        - ./web:/usr/share/nginx/html/
        #Configuração do proxy reverso
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      ports:
        - 80:80
      networks: 
        - web
        #Esse depends orquestra os serviços, ou seja, ele inicia os serviços
        # que não dependem de ninguém
        # E ele valida quando tentar subir um serviço específico, por exemplo:
        #se tentar subir o frontend, ele vai verificar que este precisa do app.
      depends_on:
        - app
    app:
      image: python:3.6
      volumes:
      #Aplicação
        - ./app:/app
      working_dir: /app
      command: bash ./app.sh
      networks: 
        - banco
        - web
        - fila
      depends_on:
        - db
        - queue
      environment:
        - DB_NAME=email_sender
    queue:
      image: redis:3.2
      networks: 
        - fila
    worker:
      build: worker
      volumes:
        - ./worker:/worker
      working_dir: /worker
      command: worker.py
      networks: 
        - fila
      depends_on:
        - queue